algoritmo "salario reajuste"
// Função :
// Autor :
// Data : 10/09/2016
// Seção de Declarações 
var
idade : inteiro
nome, cargo : caracter
salariob, salariol : real
inicio
escreval ("Digite seu nome")
leia (nome)
escreval ("Digite sua idade")
leia (idade)
escreval ("Digite seu cargo")
leia (cargo)
escreval ("Digite seu salario bruto")
leia (salariob)
salarioB <- salariob * 0.09
// Seção de Comandos
fimalgoritmo
