algoritmo "A, B trocam"
// Função :
// Autor :
// Data : 8/27/2016
// Seção de Declarações 
var
   A, B, A2:real
inicio
      escreva("Digite o valor A: ")
                      leia(A)
      escreva("Digite o valor B: ")
                      leia(B)
                             A2:=A
                             A:=B
                             B:=A2

      escreval("O valor de A é: ", A)
      escreva("O valor de B é: ", B)
      
      
fimalgoritmo
