algoritmo "calculosinteiroreal"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações 
var
   a, b, c, d, ed, f, g, h : real

inicio
    a <- (20-15)/2
    escreval(a)
    b <- 20-15/2
    escreval(b)
    c <- 2*5/20 + 30/15*2
    escreval(c)
    d <- 2*(5/20) + 30(15*2)
    escreval(d)
    ed <- 23 / 4
    escreval(ed)
    f <- 23 % 4
    escreval (f)
    g <- 35 div 6+2
    escreval (g)
    h <- 35 div 6-2
    escreval (h)
    
// Seção de Comandos 
fimalgoritmo
