algoritmo "celsiusFahrenheit"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações 
var
   c,f: real
inicio
// Seção de Comandos 
   escreval("Digite a temperatura em graus celsius para ser convertida em graus fahrenheit: ")
   leia(c)
   f <- ((9*c+160)/5)
   escreval("A temperatura em graus celsius é : ", c ,"C")
   escreval("Esta mesma temperatura em fahrenheit é :", f , "F")
fimalgoritmo
