algoritmo "olhosAzuis"
// Função :
// Autor :
// Data : 03/09/2016
// Seção de Declarações 
var
   sexo : caracter
   corDosOlhos : caracter
   i, idade : inteiro
   pessoas : inteiro
inicio
// Seção de Comandos 
   pessoas<- 5
   Escreval("A cor dos olhos A = azul, V para verdes e C para castanhos")
   para i de 1 ate pessoas passo 1 faca
        escreval("Digite a cor dos olhos :")
        leia(corDosOlhos)
   fimpara
   escreval(corDosOlhos)
   
fimalgoritmo
