algoritmo "semnome"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações
var
n1, n2, n3, media :real
inicio
Escreval("Digite a primeira nota")
leia(n1)
Escreval("Digite a segunda nota")
leia(n2)
Escreval("Digite a terceira nota")
leia(n3)
media <- (n1+n2+n3)/3
      se media>=7 entao
         escreval("O aluno esta aprovado")
      senao
           escreval("O aluno esta reprovado")
      fimse
fimalgoritmo
