algoritmo "semnome"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações
var
n1, n2, dif :inteiro
inicio
Escreval("Digite o primeiro numero")
leia(n1)
Escreval("Digite o segundo numero")
leia(n2)
      se n1>n2 entao
       dif <- n1-n2
         escreval(n1," e maior que ",n2," e a diferença entre eles e: ",dif)
      senao
      dif <- n2-n1
           escreval(n2," e maior que ",n1," e a diferença entre eles e:", dif)
      fimse
fimalgoritmo
