algoritmo "semnome"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações
var
n1 :inteiro
inicio
Escreval("Digite um numero")
leia(n1)
se (n1 MOD 2 = 0) entao
   escreval(n1," é um numero par")
                  senao
                       escreval(n1, " é impar")
fimse
     se (n1>=0) entao
        escreval(n1," é um numero positivo")
                       senao
                            escreval(m1, " é um numero negativo")
     fimse
fimalgoritmo
