algoritmo "Mercado"
// Função :
// Autor :
// Data : 8/20/2016
// Seção de Declarações 
var
compra, pago, troco : Real
inicio
      escreval ("Entre com o valor da compra: ")
               leia (compra)
      escreval ("Entre com o valor pago: ")
               leia (pago)
                    troco:= (pago-compra)
      escreval ("O valor do troco é ", troco, " Reais")
      
      
      
      
      
      
fimalgoritmo
