algoritmo "Mercado"
// Função :
// Autor :
// Data : 8/20/2016
// Seção de Declarações 
var
compra, pago, troco : Real
inicio
      escreva ("Entre com o valor da compra: R$ ")
               leia (compra)
      escreva ("Entre com o valor pago: R$ ")
               leia (pago)
                    troco:= (pago-compra)
      escreval ("O valor do troco é: R$ ", troco, " Reais")
      
      
      
      
      
      
fimalgoritmo
