algoritmo "semnome"
// Função :
// Autor :
// Data : 13/08/2016
// Seção de Declarações 
var
idade1, idade2, idade3, idade4, idade5, resultado : inteiro
inicio
escreval ("idade 1")
leia (idade1)
escreval ("idade 2")
leia (idade2)
escreval ("idade 3")
leia (idade3)
escreval ("idade 4")
leia (idade4)
escreval ("idade 5")
leia (idade5)
resultado <-(idade1 + idade2 + idade3 + idade4 + idade5) div 5
escreval ("A média de idade é:", resultado)
// Seção de Comandos 
fimalgoritmo
