algoritmo "semnome"
// Função :
// Autor :
// Data : 9/10/2016
// Seção de Declarações 
var
   num : vetor [0..4] de inteiro
   i : inteiro
inicio
      para i de 0 ate 4 passo 1 faca
           escreval("Digite o ", (i+1), "º valor: ")
           leia(num[i])
      fimpara
      para i de 0 ate 4 passo 1 faca
           escreval("O ",(i+1), "º valor foi: ", num[i])
      fimpara
      
fimalgoritmo

