algoritmo "Media de Idade"

var
   a, b, c, d, f, soma : inteiro
   media : Real
inicio
      escreva("Digite a Primeira Idade: ")
      leia (a)
      escreva("Digite a Segunda Idade: ")
      leia (b)
      escreva("Digite a Terceira Idade: ")
      leia (c)
      escreva("Digite a Quarta Idade: ")
      leia (d)
      escreva("Digite a Quarta Idade: ")
      leia (f)
      soma <- (a + b + c + d + f)
      media <- (soma / 5)
      escreval("A Média de Idade é: ", media)
fimalgoritmo
