algoritmo "ExercicioMediaIdades"

var
   idade1, idade2, idade3, idade4, idade5, media : inteiro
inicio
      escreva("Idade 1: ")
      leia(idade1)
      escreva("Idade 2: ")
      leia(idade2)
      escreva("Idade 3: ")
      leia(idade3)
      escreva("Idade 4: ")
      leia(idade4)
      escreva("Idade 5: ")
      leia(idade5)
      media <- (idade1 + idade2 + idade3 + idade4 + idade5) div 5
      escreva("A média das idade é: ", media)
fimalgoritmo
