algoritmo "semnome"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações
var
E, F, G, H, b, c : inteiro
A, B, C, D : real
inicio
b <- 1
c <- 2
A <- ((20 - 15)/(2*b)
B <- 20 - 15/(2*c)
C <- 2*5/20 + 30/15*2
D <- 2*(5/20) + 30/(15*2)
E <- 23 div 4
F <- 23 mod 4
G <- 35 div 6 + 2
H <-35 div 6 - 2

Escreval(a," real")
Escreval(b," real")
Escreval(c," real")
Escreval(d," real")
Escreval(e," inteiro")
Escreval(f," inteiro")
Escreval(g," inteiro")
Escreval(h," inteiro")

fimalgoritmo
