algoritmo "semnome"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações
var
idade :inteiro
nome :caractere
salario :real
hab :logico
inicio
Escreval("Digite a idade")
Leia(idade)
escreval("Digite o nome")
Leia (nome)
Escreval("Digite o salario")
Leia(salario)
Escreval("possui habilitação? Verdadeiro ou falso?")
leia(hab)
se(hab=verdadeiro) entao
   escreval("vc esta apto a dirigir")
senao
   escreval("vc não esta apto a dirigir pois nao possui habilitação")
fimse
fimalgoritmo
