algoritmo "exercício 3"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações 
var
 nome:caractere
 idade:inteiro
 salario:real
 feminino:logico
inicio
      nome <- "gabriel"
      idade <- 16
      salario <- 1750,50
      feminino <- falso
      escreval("Nome:",nome)
      escreval("idade", idade)
      escreval("salario", salario)
      escreval("feminino", feminino)
fimalgoritmo
