algoritmo "Area do Triangulo"
// Função :
// Autor :
// Data : 8/27/2016
// Seção de Declarações 
var
   area, base, altura: real
inicio
         escreva("Digite a base do triangulo: ")
                 leia(base)
         escreva("Digite a altura do triangulo: ")
                 leia(altura)
                             area:= base*altura/2
         escreval("A área do triangulo é: ", area)
                 

                 
fimalgoritmo
