algoritmo "semnome"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações 
var
    nome:caractere
    telefone:inteiro
    endereco:caractere
    idade:inteiro
inicio
    nome <- "gabriel"
    telefone <- 32721390
    endereco <- "rua antonio jose zimmermman"
    idade <- 16
    escreval("nome:",nome)
    escreval("telefone:",telefone)
    escreval("endereco:",endereco)
    escreval("idade:",idade)
    
fimalgoritmo
