algoritmo "semnome"
// Função :
// Autor :
// Data : 10/09/2016
// Seção de Declarações 
var
numero : vetor [1..10] de real
i : inteiro
inicio
      para i de 1 ate 10 faca
           escreval ("Digite um numero")
           leia (numero[i])
           numero[i] <- numero[i] / 2
           escreval ("a metade é :", numero[i])
      fimpara
      //para i de 1 ate 10 faca
             //escreval (numero[i])
      //fimpara
// Seção de Comandos 
fimalgoritmo
