algoritmo "M2xA2.E2_qual_maior"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações 
var
n1, n2: real

inicio
      Escreval ("Insira um numero real (pos ou neg): ")
      Leia (n1)
      Escreval ("Insira um numero real (pos ou neg): ")
      Leia (n2)
      se n1 > n2 entao
         Escreva ("O numero maior é:", n1)
      senao
         Escreva ("O numero maior é:", n2)
      fimse
fimalgoritmo
