algoritmo "semnome"
// Função :
// Autor :
// Data : 03/09/2016
// Seção de Declarações 
var
nome1, nome2, nome3, nome4, nome5, olhos, sexo : caractere
idade1, idade2, idade3, idade4, idade5 : inteiro

inicio
escreval ("digite seu  nome")
leia (nome1)
escreval ("sexo 1-masculino 2-feminino")
leia (sexo)
escreval ("cor dos olhos: A - azuis V - verdes C - castanhos")
leia (olhos)
escreval ("digite sua idade: ")
leia (idade1)


// Seção de Comandos 
fimalgoritmo
