algoritmo "semnome"
// Função :
// Autor :
// Data : 03/09/2016
// Seção de Declarações 
var
nota, soma, media : real
contador : inteiro
Aluno : caractere
inicio
      contador <- 1
      escreval ("digite o nome do Aluno")
      leia (Aluno)
      enquanto contador  <= 4 faca
      escreval ("digite a nota ", contador, ":")
      leia (nota)
      contador <- contador + 1
      soma <- (contador + nota) + 1
      fimenquanto
// Seção de Comandos 
fimalgoritmo
