algoritmo "Maior Valor"
// Função :
// Autor :
// Data : 27/08/2016
// Seção de Declarações 
var
   valor1, valor2 :inteiro
inicio
      escreval ("Digite o valor um")
      leia (Valor1)
      escreval ("Digite o valor dois")
      leia (Valor2)
      se Valor1 > valor2 entao
      escreva ("valor um é maior que valor dois")
      senao
      escreva ("valor dois é maior que valor um")
      fimse

// Seção de Comandos 
fimalgoritmo
